const AUTH_PREFIX = "/auth";
const USER_PREFIX = "/users";
const TIME_ENTRY_PREFIX = "/time-entries";
const USER_REQUEST_PREFIX = "/user-requests";
const REQUEST_TYPES_PREFIX = "/request-types";
const COMPANY_PREFIX = "/companies";
const COMPANY_POLICIES_PREFIX = "/company-policies";
const EMPLOYMENT_HISTORIES_PREFIX = "/employment-histories";
const DAYS_OF_WEEK_PREFIX = "/days-of-week";

export const API_URL = {
	AUTH: {
		LOGIN: `${AUTH_PREFIX}/login`,
		REGISTER: `${AUTH_PREFIX}/register`,
		LOGOUT: `${AUTH_PREFIX}/logout`,
		CHANGE_PASSWORD: `${AUTH_PREFIX}/change-password`,
		REFRESH_ACCESS_TOKEN: `${AUTH_PREFIX}/refresh-access-token`,
		FORGOT_PASSWORD: `${AUTH_PREFIX}/forgot-password`,
		RESET_PASSWORD: `${AUTH_PREFIX}/reset-password`,
		VERIFY_ACCOUNT: `${AUTH_PREFIX}/verify-account`,
		VERIFY_TOKEN: `${AUTH_PREFIX}/verify-token`,
		GET_RESOURCE_PERMISSIONS: `${AUTH_PREFIX}/resrouce-permissions`,
		GET_ACTION_PERMISSIONS: `${AUTH_PREFIX}/action-permissions`,
		VERIFY_REFRESH_TOKEN: `${AUTH_PREFIX}/verify-refresh-token`,
		RESEND_VERIFY_ACCOUNT: `${AUTH_PREFIX}/resend-verify-account`,
	},

	USER: {
		GET_PROFILE: `${USER_PREFIX}/profile`,
		GET_ALL: USER_PREFIX,
		GET_BY_ID: `${USER_PREFIX}/:id`,
		UPDATE: `${USER_PREFIX}/:id`,
		UPDATE_PROFILE: `${USER_PREFIX}/update-profile`,
		DELETE: `${USER_PREFIX}/:id`,
		GET_APPROVERS: `${USER_PREFIX}/approvers`,
		GET_REQUESTERS: `${USER_PREFIX}/requesters`,
		EXPORT_EXCEL: `${USER_PREFIX}/export`,
	},

	COMPANY: {
		GET_OWN_COMPANY: COMPANY_PREFIX,
		GET_All_COMPANIES: `${COMPANY_PREFIX}/all`,
		CREATE_COMPANY: COMPANY_PREFIX,
		DELETE_COMPANY: `${COMPANY_PREFIX}/:id`,
		UPDATE_COMPANY: `${COMPANY_PREFIX}/:id`,
	},

	ROLE: {
		GET_ROLES: "/roles",
		ADD_ROLE: "/roles",
		DELETE_ROLE: "/roles/:id",
		EDIT_ROLE: "/roles/:id",
		ASSIGN_ROLE: `${USER_PREFIX}/assign/:id`,
	},

	PERMISSION: {
		UPDATE_PERMISSION: "/roles/assign-permissions",
	},

	TIME_ENTRY: {
		GET_TIME_ENTRY_TODAY: `${TIME_ENTRY_PREFIX}/today`,
		CHECK_IN_TIME_ENTRY: `${TIME_ENTRY_PREFIX}/check-in`,
		CHECK_OUT_TIME_ENTRY: `${TIME_ENTRY_PREFIX}/check-out`,
		GET_ALL_TIME_ENTRIES: `${TIME_ENTRY_PREFIX}/all`,
		GET_OWN_TIME_ENTRIES: TIME_ENTRY_PREFIX,
		EXPORT_EXCEL: `${TIME_ENTRY_PREFIX}/export`,
	},

	USER_REQUEST: {
		GET_ALL_REQUESTS: `${USER_REQUEST_PREFIX}/all`,
		GET_OWN_REQUESTS: USER_REQUEST_PREFIX,
		CREATE_REQUEST: `${USER_REQUEST_PREFIX}/create`,
		CREATE_HOLIDAY_REQUEST: `${USER_REQUEST_PREFIX}/create-holiday`,
		APPROVE_REQUEST: `${USER_REQUEST_PREFIX}/approve`,
		REJECT_REQUEST: `${USER_REQUEST_PREFIX}/reject`,
		DELETE_OWN_REQUESTS: `${USER_REQUEST_PREFIX}/delete`,
		APPROVER_DELETE_REQUESTS: `${USER_REQUEST_PREFIX}/approver-delete`,
	},

	COMPANY_POLICY: {
		CREATE: `${COMPANY_POLICIES_PREFIX}/create`,
		GET_ALL_COMPANY_POLICIES: `${COMPANY_POLICIES_PREFIX}/all`,
		GET_OWN_COMPANY_POLICY: COMPANY_POLICIES_PREFIX,
		GET_COMPANY_POLICY_BY_USER_ID: `${COMPANY_POLICIES_PREFIX}/:userId`,
		UPDATE: `${COMPANY_POLICIES_PREFIX}/:id`,
		DELETE: `${COMPANY_POLICIES_PREFIX}/:id`,
	},

	REQUEST_TYPES: {
		GET_OWN_REQUEST_TYPES: REQUEST_TYPES_PREFIX,
		GET_ALL_REQUEST_TYPES: `${REQUEST_TYPES_PREFIX}/all`,
	},

	EMPLOYMENT_HISTORIES: {
		GET_ALL_EMPLOYMENT_HISTORIES: `${EMPLOYMENT_HISTORIES_PREFIX}/all`,
		GET_OWN_EMPLOYMENT_HISTORIES: EMPLOYMENT_HISTORIES_PREFIX,
		UPDATE_EMPLOYMENT_HISTORY: `${EMPLOYMENT_HISTORIES_PREFIX}/:id`,
	},

	DAYS_OF_WEEK: {
		GET_ALL_DAYS_OF_WEEK: DAYS_OF_WEEK_PREFIX,
	},
};
